name: "Deployment"
# the event that will trigger the action
on: push

# what the action will do
jobs:
  test:
    # the operating system it will run on
    runs-on: ubuntu-latest
    # the list of steps that the action will go through
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Install Dependencies"
        run: yarn
      - name: "Build"
        run: yarn build
      - name: "Github Pages Deployment"
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy -u "github-actions-bot <support+actions@github.com>"
        if: ${{ github.ref == 'refs/heads/main' }} # only deploy main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
